'''
Function which counts each word in a string
'''
f = open('count_word_check.txt', 'r')

def count_func(my_str):
    '''
    INPUT: String from count_word_check.txt (generated by forloop in __init__)
    Splits the String and counts the words
    OUTPUT: Number of independent words
    '''
    my_str_list = list(my_str.split())
    length = len(my_str_list)
    return length

if __name__ == "__main__":
    my_str = ""
    for word in f:
        my_str = my_str + word

    my_count_func = count_func(my_str)
    print(my_count_func)